settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: issuing-service
    path: .
    commands:
      run:
        status: true
        method: /go/bin/issuing-service
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
