FROM golang:1.13-alpine3.10

ENV GOPATH /go
ENV GO111MODULE on

RUN apk add --update --no-cache \
    git \
    make \
    bash

WORKDIR /go/src/github.com/cosmtrek/air
RUN git clone https://github.com/cosmtrek/air.git .
RUN make ci && make install

COPY ./issuing-service /go/src/github.com/lastrust/issuing-service

COPY ./issuing-service/pkg/cert-issuer /cert-issuer-cli
COPY ./issuing-service/pkg/cert-issuer/conf_regtest.ini /etc/cert-issuer/conf.ini

RUN apk add --update \
        bash \
        ca-certificates \
        curl \
        gcc \
        gmp-dev \
        libffi-dev \
        libressl-dev \
        linux-headers \
        make \
        musl-dev \
        python \
        python3 \
        python3-dev \
        libxslt \
        libxslt-dev \
        tar \
# For HTML to PDF converting
        nodejs nodejs-npm \
    && python3 -m ensurepip \
    && pip3 install --upgrade pip setuptools \
    && mkdir -p /etc/cert-issuer/data/unsigned_certificates \
    && mkdir /etc/cert-issuer/data/blockchain_certificates \
    && pip3 install /cert-issuer-cli/. \
    && rm -r /usr/lib/python*/ensurepip \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache \
    && sed -i.bak s/==1\.0b1/\>=1\.0\.2/g /usr/lib/python3.*/site-packages/merkletools-1.0.2-py3.*.egg-info/requires.txt

# install cert-issuer cli
WORKDIR /cert-issuer-cli
RUN python3 setup.py experimental --blockchain=ethereum

# install htmltopdf cli
WORKDIR /go/src/github.com/lastrust/issuing-service/pkg/htmltopdf
COPY ./issuing-service/pkg/htmltopdf /app/pkg/htmltopdf
RUN sed -i -e 's/v3.11/edge/g' /etc/apk/repositories \
    && apk add --no-cache \
    openjdk8-jre-base \
    # chromium dependencies
    nss \
    chromium-chromedriver \
    chromium \
    && apk upgrade --no-cache --available
ENV CHROME_BIN /usr/bin/chromium-browser
RUN npm ci

COPY ./storage /storage

WORKDIR /go/src/github.com/lastrust/issuing-service
ENV GOFLAGS -mod=vendor
CMD [ "air", "-d" ]

